CREATE TABLE "candidatos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "data_nascimento" date NOT NULL,
  "email" varchar(50) UNIQUE NOT NULL,
  "cpf" varchar(11) UNIQUE NOT NULL,
  "pais" varchar(30) NOT NULL,
  "cep" varchar(20) NOT NULL,
  "senha" varchar(255) NOT NULL
);

CREATE TABLE "competencias" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL
);

CREATE TABLE "candidato_competencias" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "candidato_id" integer,
  "competencias_id" integer,
  "nivel" varchar
);

CREATE TABLE "empresas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "cnpj" varchar NOT NULL,
  "descricao" text NOT NULL,
  "pais" varchar(30),
  "cep" varchar(20),
  "senha" varchar(255) NOT NULL
);

CREATE TABLE "vagas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "descricao" text NOT NULL,
  "competencias" varchar NOT NULL,
  "local" varchar,
  "empresa_id" integer
);

CREATE TABLE "vaga_competencias" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vaga_id" integer,
  "competencia_id" integer
);

ALTER TABLE "candidato_competencias" ADD FOREIGN KEY ("candidato_id") REFERENCES "candidatos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "candidato_competencias" ADD FOREIGN KEY ("competencias_id") REFERENCES "competencias" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vagas" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vaga_competencias" ADD FOREIGN KEY ("vaga_id") REFERENCES "vagas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "vaga_competencias" ADD FOREIGN KEY ("competencia_id") REFERENCES "competencias" ("id") DEFERRABLE INITIALLY IMMEDIATE;

INSERT INTO competencias (nome) VALUES 
('PostgreSQL'), ('MongoDB'), ('Python'), ('React'), ('Node.js');

INSERT INTO candidatos (nome, data_nascimento, email, cpf, pais, cep, senha) VALUES 
('Ana Silva', '1995-05-15', 'ana.silva@email.com', '12345678901', 'Brasil', '01001-000', '$2b$12$K1e...hash1'),
('Bruno Costa', '1990-10-20', 'bruno.c@email.com', '23456789012', 'Brasil', '20040-002', '$2b$12$L2f...hash2'),
('Carla Souza', '1998-02-28', 'carla.dev@email.com', '34567890123', 'Brasil', '30140-001', '$2b$12$M3g...hash3'),
('Diego Lima', '1985-12-12', 'diego.lima@email.com', '45678901234', 'Brasil', '40020-000', '$2b$12$N4h...hash4'),
('Elena Martins', '2001-07-07', 'elena.m@email.com', '56789012345', 'Brasil', '50010-000', '$2b$12$O5i...hash5');

INSERT INTO empresas (nome, cnpj, descricao, pais, cep, senha) VALUES 
('Tech Solutions', '12345678000101', 'Focada em soluções cloud.', 'Brasil', '04578-000', '$2b$12$P6j...hash6'),
('SoftInova', '23456789000102', 'Inovação em apps móveis.', 'Brasil', '22250-040', '$2b$12$Q7k...hash7'),
('DataMaster', '34567890000103', 'Especialistas em Big Data.', 'Brasil', '31270-010', '$2b$12$R8l...hash8'),
('WebFlow', '45678901000104', 'Agência de design e web.', 'Brasil', '80010-000', '$2b$12$S9m...hash9'),
('Global Code', '56789012000105', 'Consultoria internacional.', 'Brasil', '90010-000', '$2b$12$T0n...hash10');

INSERT INTO candidato_competencias (candidato_id, competencias_id, nivel) VALUES 
(6, 1, 'Avançado'), 
(6, 3, 'Intermediário'),
(7, 2, 'Básico'),
(8, 4, 'Avançado'),
(10, 5, 'Intermediário');

SELECT c.nome AS Candidato, comp.nome AS Tecnologia, cc.nivel
FROM candidatos c
JOIN candidato_competencias cc ON c.id = cc.candidato_id
JOIN competencias comp ON cc.competencias_id = comp.id;

SELECT * FROM competencias